// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./.vitepress/components/Demo.vue')['default']
    Home: typeof import('./.vitepress/components/globals/home.vue')['default']
  }
}

export {}
